on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: exstad-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DOCKER_REPOSITORY
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use with SHA
        run: echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Login to Docker Registry
        run: echo "${{ secrets.PASSWORD }}" | docker login -u ${{ secrets.USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .

      - name: Tag as latest
        run: docker tag ${{ secrets.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} ${{ secrets.USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Push both tags
        run: |
          docker push ${{ secrets.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          docker push ${{ secrets.USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Logout from the Registry
        if: always()
        run: docker logout

  deploy:
    runs-on: ubuntu-latest
    environment: DOCKER_REPOSITORY
    needs: build-and-push
    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/${{ secrets.VM_USER }}/app
            ./deploy.sh
